// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxbnmitkcbgpkgdwlvyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4Ym5taXRrY2JncGtnZHdsdnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNDU0MzIsImV4cCI6MjA3NjgyMTQzMn0.WAtGI3MlW3qlCLIdEXzndUGcE9QZ0GiDxYkSj0Mrcv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});